### ISSUE TITLE
Not installing npm:jade correctly

### ISSUE THREAD

**Issue by tjbenton** [johnsoftek/plugin-jade#11]
When ever I run `jspm install` it will install jade into `jspm_packages/npm/jade@1.11.0` however the file for jade doesn't get created like it should because I'm getting an 404 error because `jspm_packages/npm/jade@1.11.0.js` doesn't exist. If I create that file and add the following contents it works correctly.

```
// jspm_packages/npm/jade@1.11.0.js
module.exports = require('npm:jade@1.11.0/lib);
```

I think this might be an issue with JSPM it's self so you might need to open an issue with them but since running `jspm install jade` installs this lib I figured I'd open the issue here.

**Comment by johnsoftek** [comment]
I agree. It is likely a problem with a later version of jspm or systemjs. I am still looking into it.

**Comment by johnsoftek** [comment]
Issue raised in jspm-cli: jspm/jspm-cli#1387
