### ISSUE TITLE
usage with babel?

### ISSUE THREAD

**Issue by psi-4ward** [johnsoftek/plugin-jade#12]
Ive installed you Plugin and setup jspm with babel.

``` javascript
import tpl from 'dash.jade!';
console.log(tpl());
```

brings me
`GET http://127.0.0.1:8080/jspm_packages/npm/jade@1.11.0.js 404 (Not Found)`

Any ideas whats wrong here?

**Comment by johnsoftek** [comment]
Closed as duplicate of #11.
