### ISSUE TITLE
Doesn't work with latest jspm 0.17 beta

### ISSUE THREAD

**Issue by jonricaurte** [johnsoftek/plugin-jade#14]
Here is my config:

```
SystemJS.config({
  typescriptOptions: {
    "tsconfig": true
  },
  transpiler: "plugin-typescript",
  packages: {
    "app": {
      "main": "main",
      "format": "system",
      "defaultExtension": "ts",
      "meta": {
        "*.ts": {
          "loader": "plugin-typescript"
        },
        "*.jade": {
          "loader": "plugin-jade"
        }
      }
    }
  }
});
```

For importing I have:

```
import jadeTemplate from './app.component.jade'; (tried with jade! too)
```

and getting: 

system.src.js:5031 GET http://127.0.0.1:8080/plugin-jade 404 (Not Found)X @ system.src.js:5031(anonymous function) @ system.src.js:5031(anonymous function) @ system.src.js:5031(anonymous function) @ system.src.js:5031(anonymous function) @ system.src.js:5031(anonymous function) @ system.src.js:5031(anonymous function) @ system.src.js:5031(anonymous function) @ system.src.js:5031(anonymous function) @ system.src.js:5031(anonymous function) @ system.src.js:5031
Error: Error: XHR error (404 Not Found) loading http://127.0.0.1:8080/plugin-jade
    Error loading http://127.0.0.1:8080/plugin-jade
    Error loading http://127.0.0.1:8080/src/app/app.component.jade as "./app.component.jade" from http://127.0.0.1:8080/src/app/app.component.ts

**Comment by jonricaurte** [comment]
So I removed it from meta and just did what I was trying to do and debugged plugin-jade. I get:

```
return 'var jade = require' + '("' + runtime_loc + '");\n\n' +
                'module.exports = ' + jade_compiler_1.default.compileClient(text);
        });
```

where runtime_loc is:  "http://127.0.0.1:8080/jspm_packages/npm/jade@1.11.0/lib/runtime.js"
and text is: div(class="test") testing"

However when I go to my code and do: console.log(app_component_jade_1)

it has a default which is  an empty object.

Also, I copied  jade_compiler_1.default.compileClient(text) to the console and it gave me this output:

```
"function template(locals) {
  var buf = [];
  var jade_mixins = {};
  var jade_interp;

  buf.push("<div class=\"test\">testing</div>");;return buf.join("");
}"
```

**Comment by johnsoftek** [comment]
@jonricaurte Looking into this problem. However, I cannot even get jspm@beta to load a simple package, so it may take time to reproduce this issue.

**Comment by jonricaurte** [comment]
@johnsoftek I just followed this guide and tried adding a jade template: 

http://jspm.io/0.17-beta-guide/

**Comment by johnsoftek** [comment]
@jonricaurte I missed the new script tag required by beta 17:

```
 <script src="jspm.browser.js"></script>
```

This overcomes the XHR error.

Unfortunately, the jade-plugin test then failed with another error: text not found.This error refers to the text plugin used by jade-plugin. Unfortunately, the jspm beta does not configure the text plugin in jspm.config.js.

So install the text plugin:

```
jspm i text
```

Don't forget the script tag mentioned above.

**Comment by jonricaurte** [comment]
I'm still getting the same errors @johnsoftek Is it possible to have a sample app on how you set up the jade plugin to work with jspm 0.17 betas? Thanks.

**Comment by jonricaurte** [comment]
I changed the format to esm from system here:

```
SystemJS.config({
  typescriptOptions: {
    "tsconfig": true
  },
  transpiler: "plugin-typescript",
  packages: {
    "app": {
      "main": "main",
      "format": "esm",
      "defaultExtension": "ts",
      "meta": {
        "*.ts": {
          "loader": "plugin-typescript"
        }
      }
    }
  }
});
```

and it is now trying to load an exported template file:

```
        setters:[],
        execute: function() {
            var jade = require("http://127.0.0.1:8080/jspm_packages/npm/jade@1.11.0/lib/runtime.js");
            module.exports = function template(locals) {
                var buf = [];
                var jade_mixins = {};
                var jade_interp;
                buf.push("<div class=\"test\">testing</div>");
                ;
                return buf.join("");
            };
        }
    }
```

Now it is saying require is undefined. I'm using Typescript and cannot use the esm format and have to use the system format. So it is not possible to have plugin-jade in the meta configuration because it is using the text plugin?

**Comment by jonricaurte** [comment]
I figured out the issue. When loading from typescript, you cannot not have formats in both jspm and tsconfig:

```
{
 "compilerOptions": {
    "target": "es5",                /* target of the compilation (es5) */
    "module": "system",             /* System.register([dependencies], function) (in JS)*/
    "moduleResolution": "node",     /* how module gets resolved (needed for Angular 2)*/
    "emitDecoratorMetadata": true,  /* needed for decorators */
    "experimentalDecorators": true, /* needed for decorators (@Injectable) */
    "noImplicitAny": false,          /* any has to be written explicity*/
    "sourceMap": false,
    "inlineSourceMap": false
  },
  "exclude": [   /* since compiling these packages could take ages, we want to ignore them*/
    "jspm_packages",
    "node_modules"
  ],
  "compileOnSave": false        /* on default the compiler will create js files */
}
```

then in my jspm config i had:

```
SystemJS.config({
  typescriptOptions: {
    "tsconfig": true
  },
  transpiler: "plugin-typescript",
  packages: {
    "app": {
      "main": "main",
      "format": "system",
      "defaultExtension": "ts",
      "meta": {
        "*.ts": {
          "loader": "plugin-typescript"
        }
      }
    }
  }
});
```

When I remove the format from the jspm config it works, so it should look like this:

```
SystemJS.config({
  typescriptOptions: {
    "tsconfig": true
  },
  transpiler: "plugin-typescript",
  packages: {
    "app": {
      "main": "main",
      "defaultExtension": "ts",
      "meta": {
        "*.ts": {
          "loader": "plugin-typescript"
        }
      }
    }
  }
});
```

**Comment by johnsoftek** [comment]
@jonricaurte With help from @guybedford, I was able to dispense with the text plugin. So no need to install it with jade-plugin@0.6.1

**Comment by jonricaurte** [comment]
Nice! So we should now be able to use the loader in the meta tag for jspm 0.17? And not have to use the .jade! when importing and just .jade ? @johnsoftek

**Comment by johnsoftek** [comment]
@jonricaurte Yes.

```
SystemJS.config({
  transpiler: "plugin-babel",
  packages: {
    "test-jade": {
      "format": "esm",
      "main": "app.js",
      "meta": {
        "*.js": {
          "loader": "plugin-babel"
        }
      }
    }
  },
  meta: {
    "*.jade": {
      "loader": "jade"
    }
  }
});
```

**Comment by johnsoftek** [comment]
I have updated the README to cover loader configuration.
