### ISSUE TITLE
jspm 0.17 importing jade shows error

### ISSUE THREAD

**Issue by giuseppecrj** [johnsoftek/plugin-jade#17]
I'm trying to use the plugin with jspm 0.17.0-beta.13 and I'm getting this error whenever I try to import a file using:

`import template from './app.jade'`

output:

`err  Error on translate for myproject/app.jade at file:///Users/g/Desktop/myproject/src/app.jade
  Loading myproject/app.js
  TypeError: Cannot read property 'builder' of undefined
    at file:///Users/g/Desktop/myproject/jspm_packages/github/johnsoftek/plugin-jade@1.1.0/jade.js!transpiled:10:16`

This is my jspm.config.js top block configuration.

`SystemJS.config({
  transpiler: "plugin-babel",
  packages: {
    "myproject": {
      "main": "app.js",
      "meta": {
        "*.js": {
          "loader": "plugin-babel"
        }
      }
    }
  },
  meta: {
    "*.jade": {
      "loader": "jade"
    }
  }
});`

Also I don't believe this is in the realm of the plugin itself but is there a way to make watchman catch any changes to the jade files and compile if you're using the new `jspm bundle src/app.js -wid` command?

If you need any further clarification let me know.

Thank you so much!

**Comment by jonricaurte** [comment]
@giusepperj This is related to this comment: 

https://github.com/johnsoftek/plugin-jade/issues/15#issuecomment-215105688

**Comment by johnsoftek** [comment]
@giusepperj Try latest version 1.1.1

**Comment by johnsoftek** [comment]
Fixed, hopefully, in 1.1.2

**Comment by johnsoftek** [comment]
@giusepperj  jspm with -w switch will watch jade files loaded by plugin-jade.

**Comment by jonricaurte** [comment]
@johnsoftek works for me! Thanks a lot for the quick turn around!

**Comment by giuseppecrj** [comment]
Yup works for me as well. Thank you for the fast response @johnsoftek
