### ISSUE TITLE
Bundle doesn't work

### ISSUE THREAD

**Issue by davidblurton** [johnsoftek/plugin-jade#2]
I get the follow error when I run `jspm bundle`

```
Potentially unhandled rejection [6] TypeError: Error loading "templates/posts.jade!github:johnsoftek/plugin-jade@1.9.0" at <unknown>
Error loading "templates/posts.jade!github:johnsoftek/plugin-jade@1.9.0" from "js/app" at file:/Users/David/Aranja/aranja.com/app/js/app.js
Error loading "github:johnsoftek/plugin-jade@1.9.0/jade-compiler.min" at file:/Users/David/Aranja/aranja.com/app/jspm_packages/github/johnsoftek/plugin-jade@1.9.0/jade-compiler.min.js
Execution must define a Module instance
```

I'm calling the module as follows

```
import template from 'templates/posts.jade!'

export default data => data.forEach(post => {
  var element = document.getElementById('facebook-feed')
  element.innerHTML = template({
    posts: data
  })
})
```

Possibly related issue https://github.com/systemjs/builder/issues/22

**Comment by aams** [comment]
@davidblurton I'm guessing you are correct in relating this issue to https://github.com/systemjs/builder/issues/22. The plugin includes the browserified version of the Jade compiler and runtime. There were two reasons to use those versions:
. a jspm or systemjs problem respecting "main" in package.json
. the size of the included full Jade npm package

I am on holidays but I will try using the full Jade npm package as soon as I can.

**Comment by aams** [comment]
@davidblurton I'm guessing you are correct in relating this issue to systemjs/builder#22. The plugin includes the browserified version of the Jade compiler and runtime. There were two reasons to use those versions:
. a jspm or systemjs problem respecting "main" in package.json
. the size of the included full Jade npm package

I am on holidays but I will try using the full Jade npm package as soon as I can.

**Comment by gavriguy** [comment]
+1
I have the same problem when trying to bundle

**Comment by johnsoftek** [comment]
@guybedford I created a new branch, npm-jade to overcome this bundle error, possibly due to use of the browserified versions of Jade compiler and Jade runtime.

Steps to reproduce. In a new directory:
- `jspm install jade@npm-jade`
- `jspm install npm:jade-runtime`
- `cp jspm_packages/github/johnsoftek/plugin-jade\@npm-jade/test* .`
- `cp jspm_packages/github/johnsoftek/plugin-jade\@npm-jade/*.js .`
- `jspm install app`

results in error:

```
err  Error: Error loading "test.jade!github:johnsoftek/plugin-jade@npm-jade" at <unknown>
     Error loading "test.jade!github:johnsoftek/plugin-jade@npm-jade" from "app" at file:/Users/john/tmp/pj2-test/app.js
     Error loading "@empty" at file:/Users/john/tmp/pj2-test/@empty.js
     Error loading "@empty" from "github:johnsoftek/plugin-jade@npm-jade" at file:/Users/john/tmp/pj2-test/jspm_packages/github/johnsoftek/plugin-jade@npm-jade.js
     ENOENT, open '/Users/john/tmp/pj2-test/@empty.js'
```

Any ideas?

**Comment by guybedford** [comment]
@johnsoftek are you using the latest version of jspm?

**Comment by johnsoftek** [comment]
@guybedford I was using 0.11.0. Same error on 0.11.3

**Comment by guybedford** [comment]
Ok thanks, I've fixed this in SystemJS builder 0.7.2, should get that with `npm install -f jspm` (https://github.com/systemjs/builder/commit/cbfc0c8890dc82613f6fa3532408c9e1cb3ed98d).

**Comment by johnsoftek** [comment]
@guybedford Yes. That fixed it.

I had to make some changes to my test files to make a working bundled version. Not yet updated on Github.

When will npm be updated so that `npm install jspm` will install the correct versions?

**Comment by johnsoftek** [comment]
@davidblurton @gavriguy Bundling now works for me. Please try it out.

Note that, for now, you will need to force the correct version of systemjs by installing jspm-cli like so:
`npm install -f jspm`

**Comment by davidblurton** [comment]
Thanks, will test it out at the weekend.

**Comment by gavriguy** [comment]
Works like a charm :+1:

**Comment by johnsoftek** [comment]
@gavriguy. Great.

Please note that in new version, 0.3.0, you no longer need to install jade-runtime.The plugin installs the runtime.
