### ISSUE TITLE
Does not work with latest 0.17 beta 15

### ISSUE THREAD

**Issue by jonricaurte** [johnsoftek/plugin-jade#20]
Getting the following error with beta 15:

h2_app.js:4 Potentially unhandled rejection [4] Error: Invalid JSON file https://www.h2.dev/jspm_packages/github/johnsoftek/plugin-jade@1.1.2.json
    Error loading https://www.h2.dev/jspm_packages/github/johnsoftek/plugin-jade@1.1.2.json
    Error loading https://www.h2.dev/client/app/home/home.jade as "./home.jade" from https://www.h2.dev/client/app/home/home.module.js

Seems like plugin-text is having issues, too: https://github.com/jspm/jspm-cli/issues/1848

All I did was npm uninstall jspm and then npm install jspm@beta --save-dev

**Comment by johnsoftek** [comment]
That file is created by jspm. Please raise an issue on jspm-cli

**Comment by jonricaurte** [comment]
@johnsoftek looks like when updating I had to reinstall all plugins.
