### ISSUE TITLE
running test with Karma

### ISSUE THREAD

**Issue by gavriguy** [johnsoftek/plugin-jade#3]
Hi,
Any idea how can I config Karma (karma.conf.js) to support js files that import jade files through plugin-jade.

I've tried using `karma-jade-preprocessor` but with no luck I get `Uncaught Error loading "app/app.jade!github:johnsoftek/plugin-jade@0.2.0"`

here is my conf file for reference: https://gist.github.com/gavriguy/7c55db0263ef367787aa/ca4547dd05a878f73dbc2c64e97a37d2d0a0a2f6

**Comment by johnsoftek** [comment]
Please try plugin-jade@0.4.0

**Comment by gavriguy** [comment]
Thanks I managed to make it work by adding the `serveFiles` options to the jspm config:

```
  jspm: {
        // Edit this to your needs
        serveFiles: [
          'app/**/*.jade',
          'app/**/*.css'
        ],
        loadFiles: [
          'app/**/*.js'
        ]
    },
```

see the update gist:
https://gist.github.com/gavriguy/7c55db0263ef367787aa/revisions
